# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "QSKIT"
version = "1.0.0"
description = "QSKIT using pyproject.toml"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Xian-Yong Ding", 
    email = "dxy_vasp@163.com",
    instution="ChongQing Normal University"}
]
dependencies = [
    "requests>=2.25.1",
    "numpy>=1.21.0",
    "pandas>=",
]

[project.scripts]
mycli = "src.QSKIT:main"
